### ISSUE TITLE
Remote Rsync as Source

### ISSUE THREAD

**Issue by ItsNoted** [ich777/docker-luckybackup#2]
Hey there!

I hope you are taking support here on the github as I don't use Unraid. I am trying to use the rsync remote host as a source but I can't seem to grasp how to use the password file. I keep getting the following error.

![chrome_bPxN1RaFYQ](https://github.com/ich777/docker-luckybackup/assets/57927413/4c619f39-d7d2-4191-b675-ad534231a4de)

**Comment by ich777** [comment]
Sure thing, I have also no issue giving support on the Unraid Forums for different distributions.

> I keep getting the following error.

TBH I've never tried it with a password file, I always recommend using your ssh keys for the connection since this is working reliably for my.
The only thing that you have to do, regardless if you run it as root or not, from the /luckybackup/.ssh directory and not from the /root/.ssh directory.

[Here](https://unraid.net/blog/unraid-server-backups-with-luckybackup) is a tutorial but sadly enough with the /root directory instead of the /luckybackup directory.

I can of course look into the password file too but as said above I recommend doing it with the ssh keys. Please let me know if this is also a viable solution for you and let me also know if you need help.

**Comment by ich777** [comment]
Closing this issue due to no response, feel free to open up the issue again.
